tidy up white space

diff --git a/salt/pi/rtc/load-rtc b/salt/pi/rtc/load-rtc
--- a/salt/pi/rtc/load-rtc
+++ b/salt/pi/rtc/load-rtc
@@ -4,21 +4,21 @@
 
 set -e
 if [ $EUID -ne 0 ]; then
-    echo "run as root"
-    exit 1
+  echo "run as root"
+  exit 1
 fi
 
 i=10
 until /sbin/hwclock -r
 do
-	if [[ $i -le  0 ]]; then
-		exit
-	fi
-	echo "failed to read RTC. Will try $i more times"
+  if [[ $i -le  0 ]]; then
+    exit
+  fi
+  echo "failed to read RTC. Will try $i more times"
   /sbin/modprobe -r rtc_pcf8523
   /sbin/modprobe rtc_pcf8523
-	((i--))
-	sleep 6s
+  ((i--))
+  sleep 6s
 done
 echo "RTC read successful"
 
